#########################################################################################
#   Resources - Secrets
#########################################################################################

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: multiProductUser
  title: multiProductUser
  description: Run test case for BVMultiProduct with user token
  tags:
    - secret
    - security
    - mobile-sdk
    - mobile
  links:
    - url: https://bazaarvoice.atlassian.net/wiki/spaces/DEV/pages/78625898606/MOBILE+SDK+-Secrets+Catalog
      title: Internal Rotation Documentation
      icon: docs
spec:
  type: secret
  system: mobile-sdk
  owner: mobile-sdk
  lifecycle: production
  dependsOn:
    - resource:aws-secrets-manager

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: progressiveReviewUser
  title: progressiveReviewUser
  description: Run test case for BVProgressiveReview with user token
  tags:
    - secret
    - security
    - mobile-sdk
    - mobile
  links:
    - url: https://bazaarvoice.atlassian.net/wiki/spaces/DEV/pages/78625898606/MOBILE+SDK+-Secrets+Catalog
      title: Internal Rotation Documentation
      icon: docs
spec:
  type: secret
  system: mobile-sdk
  owner: mobile-sdk
  lifecycle: production
  dependsOn:
    - resource:aws-secrets-manager

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildRequestSession
  title: buildRequestSession
  description: Run test case for BVProgressiveReview with session token
  tags:
    - secret
    - security
    - mobile-sdk
    - mobile
  links:
    - url: https://bazaarvoice.atlassian.net/wiki/spaces/DEV/pages/78625898606/MOBILE+SDK+-Secrets+Catalog
      title: Internal Rotation Documentation
      icon: docs
spec:
  type: secret
  system: mobile-sdk
  owner: mobile-sdk
  lifecycle: production
  dependsOn:
    - resource:aws-secrets-manager

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildRequestFailureSession
  title: buildRequestFailureSession
  description: Run test case for BVProgressiveReview with failure session token
  tags:
    - secret
    - security
    - mobile-sdk
    - mobile
  links:
    - url: https://bazaarvoice.atlassian.net/wiki/spaces/DEV/pages/78625898606/MOBILE+SDK+-Secrets+Catalog
      title: Internal Rotation Documentation
      icon: docs
spec:
  type: secret
  system: mobile-sdk
  owner: mobile-sdk
  lifecycle: production
  dependsOn:
    - resource:aws-secrets-manager

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildRequestSuccessSession
  title: buildRequestSuccessSession
  description: Run test case for BVProgressiveReview with success session token
  tags:
    - secret
    - security
    - mobile-sdk
    - mobile
  links:
    - url: https://bazaarvoice.atlassian.net/wiki/spaces/DEV/pages/78625898606/MOBILE+SDK+-Secrets+Catalog
      title: Internal Rotation Documentation
      icon: docs
spec:
  type: secret
  system: mobile-sdk
  owner: mobile-sdk
  lifecycle: production
  dependsOn:
    - resource:aws-secrets-manager

---

#########################################################################################
#   Component
#########################################################################################

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bv-ios-swift-sdk
  github.com/project-slug: bvengineering/bv-ios-sdk-swift-dev
  description: Bazaarvoice Mobile SDK for iOS which supports Swift programming language.
  annotations:
    github.com/project-slug: bvengineering/bv-ios-sdk-swift-dev
  links:
    - url: https://github.com/bvengineering/bv-ios-sdk-swift-dev
      title: bv-ios-swift-sdk repository
  tags:
    - mobile-sdk
    - mobile
    - swift
spec:
  type: library
  lifecycle: production
  owner: mobile-sdk
  system: mobile-sdk
  dependsOn:
    - resource:multiProductUser
    - resource:progressiveReviewUser
    - resource:buildRequestSession
    - resource:buildRequestFailureSession
    - resource:buildRequestSuccessSession

---
